# Generated by Django 5.1.4 on 2026-07-09 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('family', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('causes', models.JSONField(blank=True, default=list)),
                ('organic_treatments', models.JSONField(blank=True, default=list)),
                ('chemical_treatments', models.JSONField(blank=True, default=list)),
                ('prevention_tips', models.JSONField(blank=True, default=list)),
                ('affected_parts', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('weather', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('sample_image', models.URLField(blank=True)),
                ('regional_recommendation', models.TextField(blank=True)),
                ('nearby_agricultural_office', models.CharField(blank=True, max_length=255)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='scans.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('confidence', models.FloatField()),
                ('healthy_probability', models.FloatField(default=0)),
                ('disease_probability', models.FloatField(default=0)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='scans.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('organic', 'organic'), ('chemical', 'chemical')], max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('application_method', models.CharField(blank=True, max_length=120)),
                ('safety_precautions', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='scans.disease')),
            ],
        ),
    ]
