# Generated by Django 4.2.30 on 2026-07-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseMedicineMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('application_method', models.CharField(blank=True, max_length=255)),
                ('safety_precautions', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_mappings', to='scans.disease')),
            ],
            options={
                'db_table': 'disease_medicine_mapping',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.AddField(
            model_name='diseasemedicinemapping',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_mappings', to='scans.medicine'),
        ),
        migrations.AlterUniqueTogether(
            name='diseasemedicinemapping',
            unique_together={('disease', 'medicine')},
        ),
    ]
