# Generated by Django 4.2.30 on 2026-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_diseasemedicinemapping_medicine_delete_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasemedicinemapping',
            name='application_method',
        ),
        migrations.RemoveField(
            model_name='diseasemedicinemapping',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='diseasemedicinemapping',
            name='safety_precautions',
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_ingredients',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='application_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_guidance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='medicine',
            name='safety_precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='device_information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='location_data',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
