# Generated by Django 4.2.30 on 2026-07-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='AgriVision AI', max_length=255)),
                ('application_version', models.CharField(default='1.0.0', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('prediction_threshold', models.FloatField(default=0.5)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('email_host', models.CharField(blank=True, max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_user', models.CharField(blank=True, max_length=255)),
                ('otp_expiry_minutes', models.IntegerField(default=10)),
                ('jwt_expiration_minutes', models.IntegerField(default=30)),
                ('upload_size_limit_mb', models.IntegerField(default=10)),
                ('ai_model_selection', models.CharField(default='onnx', max_length=50)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
