"""
populate_db.py — Seed the AgriVision AI database with all 38 PlantVillage
disease/healthy classes, recommended medicines, and Nepal-specific guidance.

Usage:
    python manage.py shell < populate_db.py
    OR
    python populate_db.py   (with DJANGO_SETTINGS_MODULE set)

NOTE: Treatment information has been compiled from publicly available
agricultural extension resources and the PlantVillage dataset descriptions.
Fields marked with ⚠ REVIEW should be verified against authoritative Nepal
Department of Agriculture sources before production deployment.
"""

import os
import sys
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
django.setup()

from apps.scans.models import Crop, Disease, Medicine, DiseaseMedicineMapping

# ─── Crops ─────────────────────────────────────────────────────────────────
CROPS = {
    'Apple': 'Malus domestica',
    'Blueberry': 'Vaccinium corymbosum',
    'Cherry': 'Prunus avium',
    'Corn': 'Zea mays',
    'Grape': 'Vitis vinifera',
    'Orange': 'Citrus sinensis',
    'Peach': 'Prunus persica',
    'Pepper bell': 'Capsicum annuum',
    'Potato': 'Solanum tuberosum',
    'Raspberry': 'Rubus idaeus',
    'Soybean': 'Glycine max',
    'Squash': 'Cucurbita spp.',
    'Strawberry': 'Fragaria × ananassa',
    'Tomato': 'Solanum lycopersicum',
}

# ─── Medicines ─────────────────────────────────────────────────────────────
MEDICINES_DATA = [
    {
        'name': 'Mancozeb 75% WP',
        'type': 'chemical',
        'active_ingredients': 'Mancozeb',
        'dosage_guidance': '2-3 g per litre of water',
        'application_method': 'Foliar spray at 7-10 day intervals',
        'manufacturer': 'Various (Indofil, UPL)',
        'safety_precautions': 'Wear protective clothing. Do not apply within 7 days of harvest.',
        'description': 'Broad-spectrum contact fungicide effective against many foliar diseases.',
    },
    {
        'name': 'Copper Oxychloride 50% WP',
        'type': 'chemical',
        'active_ingredients': 'Copper Oxychloride',
        'dosage_guidance': '3 g per litre of water',
        'application_method': 'Foliar spray at first sign of disease',
        'manufacturer': 'Various',
        'safety_precautions': 'Avoid use in hot weather to prevent phytotoxicity.',
        'description': 'Copper-based protective fungicide widely used in Nepal.',
    },
    {
        'name': 'Metalaxyl + Mancozeb (Ridomil Gold)',
        'type': 'chemical',
        'active_ingredients': 'Metalaxyl 8% + Mancozeb 64%',
        'dosage_guidance': '2.5 g per litre of water',
        'application_method': 'Foliar spray, repeat at 10-14 day intervals',
        'manufacturer': 'Syngenta',
        'safety_precautions': 'Restrict the number of applications to avoid resistance.',
        'description': 'Systemic + contact fungicide effective against oomycete diseases like late blight.',
    },
    {
        'name': 'Neem Oil',
        'type': 'organic',
        'active_ingredients': 'Azadirachtin',
        'dosage_guidance': '5 ml per litre of water',
        'application_method': 'Foliar spray in the evening. Reapply every 7 days.',
        'manufacturer': 'Various (local Nepal production available)',
        'safety_precautions': 'Non-toxic to humans. Avoid spraying during full sunlight.',
        'description': 'Organic broad-spectrum insecticide and fungicide.',
    },
    {
        'name': 'Trichoderma viride',
        'type': 'organic',
        'active_ingredients': 'Trichoderma viride spores',
        'dosage_guidance': '5 g per litre of water (soil drench) or 2-3 kg per hectare',
        'application_method': 'Soil application or seed treatment',
        'manufacturer': 'Various bio-labs',
        'safety_precautions': 'Store in cool dry place. Compatible with neem-based products.',
        'description': 'Biological fungicide for soil-borne disease management.',
    },
    {
        'name': 'Chlorothalonil 75% WP',
        'type': 'chemical',
        'active_ingredients': 'Chlorothalonil',
        'dosage_guidance': '2 g per litre of water',
        'application_method': 'Foliar spray at 7-14 day intervals',
        'manufacturer': 'Syngenta (Bravo)',
        'safety_precautions': 'Eye and skin irritant. Wear PPE during application.',
        'description': 'Broad-spectrum contact fungicide for leaf spot and blight control.',
    },
    {
        'name': 'Bordeaux Mixture',
        'type': 'organic',
        'active_ingredients': 'Copper sulphate + Lime',
        'dosage_guidance': '1% solution (10 g CuSO4 + 10 g lime per litre)',
        'application_method': 'Foliar spray as preventive measure',
        'manufacturer': 'Self-prepared',
        'safety_precautions': 'Prepare fresh. Can stain equipment and clothing.',
        'description': 'Traditional copper fungicide widely used in Nepal for fruit and vegetable crops.',
    },
    {
        'name': 'Imidacloprid 17.8% SL',
        'type': 'chemical',
        'active_ingredients': 'Imidacloprid',
        'dosage_guidance': '0.5 ml per litre of water',
        'application_method': 'Foliar spray or soil drench',
        'manufacturer': 'Bayer (Confidor)',
        'safety_precautions': 'Toxic to pollinators. Do not spray during flowering.',
        'description': 'Systemic insecticide for vector control (aphids, whiteflies).',
    },
    {
        'name': 'Sulfur 80% WP',
        'type': 'chemical',
        'active_ingredients': 'Sulfur',
        'dosage_guidance': '3 g per litre of water',
        'application_method': 'Foliar spray; do not use in temperatures above 35°C',
        'manufacturer': 'Various',
        'safety_precautions': 'Can cause leaf burn in hot weather.',
        'description': 'Contact fungicide effective against powdery mildew.',
    },
    {
        'name': 'Abamectin 1.8% EC',
        'type': 'chemical',
        'active_ingredients': 'Abamectin',
        'dosage_guidance': '0.5 ml per litre of water',
        'application_method': 'Foliar spray targeting mite-infested areas',
        'manufacturer': 'Syngenta (Vertimec)',
        'safety_precautions': 'Highly toxic to aquatic organisms. Avoid drift.',
        'description': 'Acaricide/insecticide for spider mite and leafminer control.',
    },
]

# ─── Disease Data ──────────────────────────────────────────────────────────
# Each entry maps to the PlantVillage class label.

DISEASE_DATA = [
    # ── Apple ──
    {
        'class_label': 'Apple___Apple_scab',
        'crop': 'Apple',
        'name': 'Apple___Apple_scab',
        'scientific_name': 'Venturia inaequalis',
        'description': 'Apple scab is a fungal disease causing olive-green to brown lesions on leaves and fruit, leading to premature leaf drop and unmarketable fruit.',
        'symptoms': ['Olive-green to dark brown velvety spots on leaves', 'Scabby lesions on fruit surface', 'Premature leaf drop', 'Distorted and cracked fruit'],
        'causes': ['Fungal spores overwintering in fallen leaves', 'Wet spring weather with temperatures 15-25°C', 'Poor air circulation'],
        'organic_treatments': ['Apply Bordeaux mixture as preventive spray', 'Use neem oil sprays', 'Remove and destroy fallen leaves'],
        'chemical_treatments': ['Mancozeb 75% WP spray', 'Chlorothalonil spray during petal fall'],
        'prevention_tips': ['Plant resistant apple varieties', 'Ensure good air circulation through pruning', 'Remove fallen leaves in autumn', 'Apply dormant sprays before bud break'],
        'affected_parts': ['Leaves', 'Fruit', 'Twigs'],
        'severity': 'Medium',
        'duration': '2-4 weeks per infection cycle',
        'weather': 'Cool and wet (15-25°C)',
        'regional_recommendation': '⚠ REVIEW: Suitable for mid-hill districts of Nepal (Jumla, Mustang, Manang) where apple cultivation is common. Contact District Agriculture Development Office for local spray calendars.',
        'medicines': ['Mancozeb 75% WP', 'Bordeaux Mixture', 'Neem Oil', 'Chlorothalonil 75% WP'],
    },
    {
        'class_label': 'Apple___Black_rot',
        'crop': 'Apple',
        'name': 'Apple___Black_rot',
        'scientific_name': 'Botryosphaeria obtusa',
        'description': 'Black rot causes leaf spots, fruit rot, and cankers on limbs. Infected fruit develops a characteristic brown-to-black rot often starting at the calyx end.',
        'symptoms': ['Frogeye leaf spots (brown center with purple margin)', 'Black rotting of fruit', 'Cankers on branches', 'Mummified fruit remaining on tree'],
        'causes': ['Fungus overwinters in mummified fruit and cankers', 'Warm wet weather (20-30°C)', 'Wounds from insects or hail'],
        'organic_treatments': ['Remove mummified fruit and cankered wood', 'Apply neem oil', 'Bordeaux mixture spray'],
        'chemical_treatments': ['Mancozeb spray during growing season', 'Copper oxychloride application'],
        'prevention_tips': ['Remove dead wood and mummified fruit', 'Maintain tree vigor through proper fertilization', 'Avoid wounding fruit during harvest'],
        'affected_parts': ['Fruit', 'Leaves', 'Branches'],
        'severity': 'High',
        'duration': 'Season-long if untreated',
        'weather': 'Warm and humid',
        'regional_recommendation': '⚠ REVIEW: Important in apple-growing areas of Jumla and Mustang. Proper orchard sanitation is critical in Nepal\'s monsoon climate.',
        'medicines': ['Mancozeb 75% WP', 'Copper Oxychloride 50% WP', 'Neem Oil'],
    },
    {
        'class_label': 'Apple___Cedar_apple_rust',
        'crop': 'Apple',
        'name': 'Apple___Cedar_apple_rust',
        'scientific_name': 'Gymnosporangium juniperi-virginianae',
        'description': 'Cedar apple rust produces bright orange-yellow spots on apple leaves and fruit. The fungus requires both apple and juniper/cedar as alternate hosts.',
        'symptoms': ['Bright yellow-orange spots on upper leaf surface', 'Small tube-like structures on leaf undersides', 'Spots on fruit surface', 'Premature defoliation'],
        'causes': ['Fungus alternates between apple and juniper hosts', 'Spring rains carrying spores from nearby junipers', 'Warm wet weather'],
        'organic_treatments': ['Remove nearby juniper/cedar trees within 100 meters', 'Apply neem oil', 'Bordeaux mixture spray'],
        'chemical_treatments': ['Mancozeb spray from pink bud to petal fall', 'Chlorothalonil application'],
        'prevention_tips': ['Plant rust-resistant apple varieties', 'Remove nearby juniper hosts', 'Apply protective fungicides during spring'],
        'affected_parts': ['Leaves', 'Fruit'],
        'severity': 'Medium',
        'duration': 'Spring infection cycle (4-6 weeks)',
        'weather': 'Warm and rainy spring',
        'regional_recommendation': '⚠ REVIEW: Less common in Nepal but possible in areas with both apple and juniper species. Consult local agricultural extension for regional host distribution.',
        'medicines': ['Mancozeb 75% WP', 'Bordeaux Mixture', 'Chlorothalonil 75% WP'],
    },
    {
        'class_label': 'Apple___healthy',
        'crop': 'Apple',
        'name': 'Apple___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The apple leaf appears healthy with no visible signs of infection.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Continue regular orchard monitoring', 'Maintain proper nutrition and irrigation', 'Practice good orchard sanitation'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: For Nepali apple growers — maintain balanced fertilization with locally available compost and DAP as recommended by the district agriculture office.',
        'medicines': [],
    },
    # ── Blueberry ──
    {
        'class_label': 'Blueberry___healthy',
        'crop': 'Blueberry',
        'name': 'Blueberry___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The blueberry leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Maintain acidic soil pH (4.5-5.5)', 'Mulch with pine needles or wood chips', 'Ensure good drainage'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Blueberry cultivation is experimental in Nepal. Suitable for cooler high-altitude regions.',
        'medicines': [],
    },
    # ── Cherry ──
    {
        'class_label': 'Cherry_(including_sour)___Powdery_mildew',
        'crop': 'Cherry',
        'name': 'Cherry_(including_sour)___Powdery_mildew',
        'scientific_name': 'Podosphaera clandestina',
        'description': 'Powdery mildew on cherry causes white powdery patches on leaves, shoots, and fruit, reducing photosynthesis and fruit quality.',
        'symptoms': ['White powdery coating on leaves', 'Curling and distortion of young leaves', 'Stunted shoot growth', 'White patches on fruit'],
        'causes': ['Warm dry days followed by cool humid nights', 'Dense canopy with poor air circulation', 'Temperatures 20-25°C with high humidity'],
        'organic_treatments': ['Sulfur-based sprays', 'Neem oil application', 'Potassium bicarbonate spray'],
        'chemical_treatments': ['Sulfur 80% WP', 'Chlorothalonil spray'],
        'prevention_tips': ['Prune to improve air circulation', 'Avoid excessive nitrogen fertilization', 'Select resistant varieties'],
        'affected_parts': ['Leaves', 'Shoots', 'Fruit'],
        'severity': 'Medium',
        'duration': '3-6 weeks if untreated',
        'weather': 'Warm days (20-25°C) with cool humid nights',
        'regional_recommendation': '⚠ REVIEW: Cherry cultivation exists in select hill districts of Nepal. Sulfur sprays are widely available locally.',
        'medicines': ['Sulfur 80% WP', 'Neem Oil'],
    },
    {
        'class_label': 'Cherry_(including_sour)___healthy',
        'crop': 'Cherry',
        'name': 'Cherry_(including_sour)___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The cherry leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Regular pruning for air circulation', 'Balanced fertilization', 'Monitor for pest damage'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Maintain good orchard practices suited to Nepal\'s mid-hill climate.',
        'medicines': [],
    },
    # ── Corn ──
    {
        'class_label': 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
        'crop': 'Corn',
        'name': 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
        'scientific_name': 'Cercospora zeae-maydis',
        'description': 'Gray leaf spot is a serious foliar disease of maize characterized by rectangular grayish-tan lesions that run parallel to leaf veins.',
        'symptoms': ['Rectangular gray-tan lesions on leaves', 'Lesions follow leaf veins', 'Severe blighting in humid conditions', 'Premature leaf death'],
        'causes': ['Fungus survives in crop residue', 'Prolonged periods of high humidity and warm temperatures', 'Continuous maize cropping'],
        'organic_treatments': ['Crop rotation with non-cereal crops', 'Remove crop residues after harvest', 'Use Trichoderma-based bioagents'],
        'chemical_treatments': ['Mancozeb 75% WP spray', 'Chlorothalonil application at tasseling'],
        'prevention_tips': ['Rotate crops (avoid maize after maize)', 'Plant resistant hybrids', 'Improve field drainage', 'Destroy crop residues'],
        'affected_parts': ['Leaves'],
        'severity': 'High',
        'duration': 'Mid-season through harvest',
        'weather': 'Warm and humid (25-30°C)',
        'regional_recommendation': '⚠ REVIEW: Major concern in the Terai and mid-hills of Nepal during the monsoon maize crop (June-September). Contact Maize Research Program, Rampur for resistant varieties.',
        'medicines': ['Mancozeb 75% WP', 'Chlorothalonil 75% WP', 'Trichoderma viride'],
    },
    {
        'class_label': 'Corn_(maize)___Common_rust_',
        'crop': 'Corn',
        'name': 'Corn_(maize)___Common_rust_',
        'scientific_name': 'Puccinia sorghi',
        'description': 'Common rust produces small reddish-brown pustules on both leaf surfaces. Severe infections reduce photosynthetic area and grain yield.',
        'symptoms': ['Small circular to elongate reddish-brown pustules on leaves', 'Pustules on both upper and lower leaf surfaces', 'Chlorotic halos around pustules', 'Severe defoliation in susceptible varieties'],
        'causes': ['Airborne urediniospores', 'Moderate temperatures (15-25°C) with high humidity', 'Susceptible maize varieties'],
        'organic_treatments': ['Plant resistant varieties', 'Remove volunteer maize plants', 'Trichoderma-based seed treatment'],
        'chemical_treatments': ['Mancozeb spray at first sign of pustules', 'Copper oxychloride spray'],
        'prevention_tips': ['Use rust-resistant hybrids', 'Adjust planting dates to avoid peak infection periods', 'Monitor fields regularly'],
        'affected_parts': ['Leaves', 'Husks'],
        'severity': 'Medium',
        'duration': 'Depends on weather; 3-6 weeks',
        'weather': 'Cool to moderate (15-25°C) with dew',
        'regional_recommendation': '⚠ REVIEW: Common in Nepal\'s mid-hill maize during spring. Use NMRP-recommended resistant varieties like Manakamana series.',
        'medicines': ['Mancozeb 75% WP', 'Copper Oxychloride 50% WP'],
    },
    {
        'class_label': 'Corn_(maize)___Northern_Leaf_Blight',
        'crop': 'Corn',
        'name': 'Corn_(maize)___Northern_Leaf_Blight',
        'scientific_name': 'Exserohilum turcicum',
        'description': 'Northern leaf blight causes large cigar-shaped gray-green to tan lesions on maize leaves, significantly reducing yield when infection occurs before tasseling.',
        'symptoms': ['Large cigar-shaped gray-green lesions (5-15 cm)', 'Lesions turn tan as they mature', 'Lower leaves affected first', 'Severe blighting of entire canopy'],
        'causes': ['Fungus survives in infected crop debris', 'Moderate temperatures with heavy dew or rain', 'Continuous maize cropping'],
        'organic_treatments': ['Deep plowing to bury crop residue', 'Crop rotation', 'Trichoderma viride soil application'],
        'chemical_treatments': ['Mancozeb 75% WP', 'Metalaxyl + Mancozeb for severe infections'],
        'prevention_tips': ['Plant resistant hybrids', 'Rotate with legumes or non-cereal crops', 'Destroy previous crop residue'],
        'affected_parts': ['Leaves'],
        'severity': 'High',
        'duration': 'Mid-season through harvest',
        'weather': 'Moderate temperature (18-27°C) with high humidity',
        'regional_recommendation': '⚠ REVIEW: A significant disease in Nepal\'s monsoon maize. NMRP Rampur has released several NLB-tolerant OPVs and hybrids.',
        'medicines': ['Mancozeb 75% WP', 'Metalaxyl + Mancozeb (Ridomil Gold)', 'Trichoderma viride'],
    },
    {
        'class_label': 'Corn_(maize)___healthy',
        'crop': 'Corn',
        'name': 'Corn_(maize)___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The maize leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Maintain balanced NPK fertilization', 'Ensure proper plant spacing', 'Monitor for pest and disease signs regularly'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: For Nepal\'s maize growers — follow NMRP Rampur recommendations for variety selection and fertilization.',
        'medicines': [],
    },
    # ── Grape ──
    {
        'class_label': 'Grape___Black_rot',
        'crop': 'Grape',
        'name': 'Grape___Black_rot',
        'scientific_name': 'Guignardia bidwellii',
        'description': 'Black rot causes brown circular lesions on leaves and a destructive black rot of berries, often resulting in complete crop loss if uncontrolled.',
        'symptoms': ['Brown circular spots with dark margins on leaves', 'Berries turn brown then black and shrivel (mummify)', 'Black pycnidia visible in lesions'],
        'causes': ['Fungus overwinters in mummified berries and cane lesions', 'Warm wet weather during bloom and fruit development', 'Poor vineyard sanitation'],
        'organic_treatments': ['Remove mummified berries', 'Bordeaux mixture spray', 'Neem oil application'],
        'chemical_treatments': ['Mancozeb spray starting at bud break', 'Copper oxychloride'],
        'prevention_tips': ['Remove mummified fruit and infected canes', 'Ensure good air circulation through canopy management', 'Spray protectively before rain events'],
        'affected_parts': ['Leaves', 'Berries', 'Canes'],
        'severity': 'High',
        'duration': 'Growing season',
        'weather': 'Warm and wet (21-32°C)',
        'regional_recommendation': '⚠ REVIEW: Grape cultivation in Nepal is concentrated in Kathmandu Valley and some Terai districts. Consult local viticulture extension for spray schedules.',
        'medicines': ['Mancozeb 75% WP', 'Copper Oxychloride 50% WP', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Grape___Esca_(Black_Measles)',
        'crop': 'Grape',
        'name': 'Grape___Esca_(Black_Measles)',
        'scientific_name': 'Phaeomoniella chlamydospora / Phaeoacremonium spp.',
        'description': 'Esca (Black Measles) is a trunk disease complex causing tiger-stripe patterns on leaves and dark spotting on berries. It is a chronic progressive condition.',
        'symptoms': ['Tiger-stripe pattern (interveinal chlorosis and necrosis) on leaves', 'Dark spots on berries (measles)', 'Sudden vine collapse (apoplexy)', 'Internal wood necrosis'],
        'causes': ['Complex of trunk-inhabiting fungi', 'Pruning wounds serve as entry points', 'Older vineyards more susceptible'],
        'organic_treatments': ['Protect pruning wounds with wound sealant', 'Trichoderma application to cuts', 'Remove severely infected vines'],
        'chemical_treatments': ['No fully effective chemical control exists', 'Copper sprays may reduce secondary infection'],
        'prevention_tips': ['Minimize large pruning wounds', 'Apply wound protectant after pruning', 'Rogue out severely infected vines'],
        'affected_parts': ['Leaves', 'Berries', 'Trunk', 'Cordons'],
        'severity': 'High',
        'duration': 'Chronic — progressive over years',
        'weather': 'Warm dry conditions trigger symptom expression',
        'regional_recommendation': '⚠ REVIEW: Trunk diseases in grape are not well-documented in Nepal. Early detection and pruning hygiene are the primary defenses.',
        'medicines': ['Trichoderma viride', 'Copper Oxychloride 50% WP'],
    },
    {
        'class_label': 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
        'crop': 'Grape',
        'name': 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
        'scientific_name': 'Pseudocercospora vitis (syn. Isariopsis clavispora)',
        'description': 'Isariopsis leaf spot causes dark brown angular spots on grape leaves, leading to early defoliation and reduced vine vigor.',
        'symptoms': ['Dark brown angular spots on leaves', 'Spots may coalesce causing large necrotic areas', 'Premature defoliation', 'Dark sporulation on leaf undersides'],
        'causes': ['Warm humid weather', 'Poor vineyard sanitation', 'Dense canopy promoting moisture retention'],
        'organic_treatments': ['Bordeaux mixture spray', 'Improve canopy management', 'Remove fallen leaves'],
        'chemical_treatments': ['Mancozeb 75% WP spray', 'Copper oxychloride'],
        'prevention_tips': ['Maintain open vine canopy', 'Proper training and trellising', 'Remove diseased leaves'],
        'affected_parts': ['Leaves'],
        'severity': 'Medium',
        'duration': '3-5 weeks per infection cycle',
        'weather': 'Warm and humid',
        'regional_recommendation': '⚠ REVIEW: Relevant for Nepal\'s grape-growing areas. Good canopy management is essential during monsoon.',
        'medicines': ['Mancozeb 75% WP', 'Copper Oxychloride 50% WP', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Grape___healthy',
        'crop': 'Grape',
        'name': 'Grape___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The grape leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Regular canopy management', 'Balanced vine nutrition', 'Monitor for pest and disease signs'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Maintain recommended vineyard practices for Nepal\'s climate conditions.',
        'medicines': [],
    },
    # ── Orange ──
    {
        'class_label': 'Orange___Haunglongbing_(Citrus_greening)',
        'crop': 'Orange',
        'name': 'Orange___Haunglongbing_(Citrus_greening)',
        'scientific_name': 'Candidatus Liberibacter asiaticus',
        'description': 'Huanglongbing (HLB / Citrus Greening) is one of the most destructive citrus diseases worldwide. It is caused by a phloem-limited bacterium transmitted by the Asian citrus psyllid.',
        'symptoms': ['Asymmetric blotchy mottling of leaves', 'Yellow shoots (yellowing of one sector)', 'Lopsided, small, green fruit', 'Bitter fruit with aborted seeds', 'Twig dieback'],
        'causes': ['Bacterium spread by Asian citrus psyllid (Diaphorina citri)', 'Grafting from infected material', 'No known cure once infected'],
        'organic_treatments': ['Control psyllid vector with neem oil sprays', 'Remove and destroy infected trees', 'Use certified disease-free planting material'],
        'chemical_treatments': ['Imidacloprid for psyllid control', 'Systemic insecticides for vector management'],
        'prevention_tips': ['Use certified disease-free nursery stock', 'Control psyllid population aggressively', 'Remove symptomatic trees promptly', 'Monitor with yellow sticky traps'],
        'affected_parts': ['Leaves', 'Fruit', 'Entire tree'],
        'severity': 'Critical',
        'duration': 'Chronic — tree decline over 3-5 years',
        'weather': 'Year-round in tropical/subtropical climates',
        'regional_recommendation': '⚠ REVIEW: HLB/Citrus Greening is a major threat to Nepal\'s mandarin orange industry (Sindhuli, Gorkha, Dhankuta). Psyllid monitoring and use of certified saplings from NARC citrus nurseries is critical.',
        'medicines': ['Imidacloprid 17.8% SL', 'Neem Oil'],
    },
    # ── Peach ──
    {
        'class_label': 'Peach___Bacterial_spot',
        'crop': 'Peach',
        'name': 'Peach___Bacterial_spot',
        'scientific_name': 'Xanthomonas arboricola pv. pruni',
        'description': 'Bacterial spot causes angular water-soaked lesions on leaves, cracking and pitting on fruit, and cankers on twigs.',
        'symptoms': ['Angular water-soaked spots on leaves', 'Shot-hole effect from fallen lesion centers', 'Sunken spots and cracking on fruit', 'Twig cankers'],
        'causes': ['Bacterium spread by rain splash and wind', 'Warm wet weather', 'Contaminated nursery stock'],
        'organic_treatments': ['Copper sprays (Bordeaux mixture)', 'Remove infected twigs', 'Avoid overhead irrigation'],
        'chemical_treatments': ['Copper oxychloride sprays', 'Copper hydroxide applications'],
        'prevention_tips': ['Plant resistant varieties', 'Avoid overhead irrigation', 'Prune to improve air circulation', 'Use disease-free nursery stock'],
        'affected_parts': ['Leaves', 'Fruit', 'Twigs'],
        'severity': 'Medium',
        'duration': 'Growing season',
        'weather': 'Warm and wet (25-30°C)',
        'regional_recommendation': '⚠ REVIEW: Peach cultivation is growing in Nepal\'s mid-hills. Copper-based sprays are the primary management tool.',
        'medicines': ['Copper Oxychloride 50% WP', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Peach___healthy',
        'crop': 'Peach',
        'name': 'Peach___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The peach leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Regular pruning', 'Balanced fertilization', 'Monitor for pests'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Maintain orchard health per NARC guidelines for mid-hill stone fruit cultivation.',
        'medicines': [],
    },
    # ── Pepper bell ──
    {
        'class_label': 'Pepper,_bell___Bacterial_spot',
        'crop': 'Pepper bell',
        'name': 'Pepper,_bell___Bacterial_spot',
        'scientific_name': 'Xanthomonas campestris pv. vesicatoria',
        'description': 'Bacterial spot of bell pepper causes water-soaked lesions on leaves and raised scab-like spots on fruit, leading to significant yield loss.',
        'symptoms': ['Small water-soaked spots on leaves', 'Spots turn brown with yellowish halo', 'Raised scab-like bumps on fruit', 'Defoliation in severe cases'],
        'causes': ['Bacterium spread by rain splash', 'Warm humid conditions', 'Contaminated seed'],
        'organic_treatments': ['Copper-based sprays (Bordeaux mixture)', 'Remove infected plants', 'Use disease-free seed'],
        'chemical_treatments': ['Copper oxychloride spray', 'Copper hydroxide'],
        'prevention_tips': ['Use certified disease-free seed', 'Avoid overhead irrigation', 'Rotate with non-solanaceous crops', 'Sanitize tools and equipment'],
        'affected_parts': ['Leaves', 'Fruit', 'Stems'],
        'severity': 'Medium',
        'duration': 'Growing season',
        'weather': 'Warm and humid (24-30°C)',
        'regional_recommendation': '⚠ REVIEW: Bell pepper/capsicum is widely grown in Nepal\'s Terai and mid-hills. IPM practices recommended by NARC are the preferred management approach.',
        'medicines': ['Copper Oxychloride 50% WP', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Pepper,_bell___healthy',
        'crop': 'Pepper bell',
        'name': 'Pepper,_bell___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The bell pepper leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Maintain proper spacing', 'Balanced fertilization', 'Regular pest monitoring'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Follow NARC vegetable production guidelines for capsicum.',
        'medicines': [],
    },
    # ── Potato ──
    {
        'class_label': 'Potato___Early_blight',
        'crop': 'Potato',
        'name': 'Potato___Early_blight',
        'scientific_name': 'Alternaria solani',
        'description': 'Early blight is characterized by dark concentric-ring lesions (target spots) on older leaves, progressing upward. It can significantly reduce tuber yield.',
        'symptoms': ['Dark brown lesions with concentric rings (target-board pattern)', 'Yellowing around lesions', 'Lower/older leaves affected first', 'Premature defoliation'],
        'causes': ['Fungus survives in crop debris and soil', 'Warm temperatures (24-29°C) with alternating wet/dry periods', 'Stressed or nutrient-deficient plants'],
        'organic_treatments': ['Remove lower affected leaves', 'Trichoderma viride soil application', 'Neem oil spray', 'Bordeaux mixture'],
        'chemical_treatments': ['Mancozeb 75% WP spray', 'Chlorothalonil spray'],
        'prevention_tips': ['Rotate crops (3-year rotation)', 'Provide adequate nutrition (avoid nitrogen stress)', 'Use certified disease-free seed tubers', 'Avoid overhead irrigation'],
        'affected_parts': ['Leaves', 'Stems', 'Tubers (rarely)'],
        'severity': 'Medium',
        'duration': '3-5 weeks per infection cycle',
        'weather': 'Warm (24-29°C) with alternating wet and dry',
        'regional_recommendation': '⚠ REVIEW: Very common in Nepal\'s potato-growing regions (Terai winter crop and mid-hill spring/autumn crops). Mancozeb is widely available through agrovets. Follow NARC Potato Research Program recommendations.',
        'medicines': ['Mancozeb 75% WP', 'Chlorothalonil 75% WP', 'Trichoderma viride', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Potato___Late_blight',
        'crop': 'Potato',
        'name': 'Potato___Late_blight',
        'scientific_name': 'Phytophthora infestans',
        'description': 'Late blight is the most devastating potato disease worldwide. It causes rapidly expanding water-soaked lesions on leaves and can destroy an entire crop within days under favorable conditions.',
        'symptoms': ['Water-soaked pale green lesions expanding rapidly', 'White fuzzy growth on leaf undersides (in humid conditions)', 'Dark brown/black necrosis of leaves and stems', 'Brown rot of tubers'],
        'causes': ['Oomycete pathogen (not a true fungus)', 'Cool wet weather (10-20°C) with persistent moisture', 'Infected seed tubers or volunteer plants'],
        'organic_treatments': ['Bordeaux mixture spray', 'Remove and destroy infected plants immediately', 'Copper-based organic sprays'],
        'chemical_treatments': ['Metalaxyl + Mancozeb (Ridomil Gold)', 'Mancozeb 75% WP spray at 7-day intervals during wet weather'],
        'prevention_tips': ['Use certified disease-free seed tubers', 'Plant resistant varieties (Kufri Jyoti, Janakdev)', 'Avoid excessive irrigation', 'Hill up soil around base of plants', 'Destroy volunteer potato plants'],
        'affected_parts': ['Leaves', 'Stems', 'Tubers'],
        'severity': 'Critical',
        'duration': 'Can destroy crop within 7-10 days in favorable conditions',
        'weather': 'Cool (10-20°C) and wet/humid',
        'regional_recommendation': '⚠ REVIEW: CRITICAL for Nepal. Late blight is the #1 potato disease in Nepal\'s mid-hills during monsoon. The National Potato Research Program (Khumaltar) recommends Metalaxyl+Mancozeb spray. Resistant varieties: Kufri Jyoti, Janakdev, Khumal Seto.',
        'medicines': ['Metalaxyl + Mancozeb (Ridomil Gold)', 'Mancozeb 75% WP', 'Bordeaux Mixture', 'Copper Oxychloride 50% WP'],
    },
    {
        'class_label': 'Potato___healthy',
        'crop': 'Potato',
        'name': 'Potato___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The potato leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Use certified seed tubers', 'Maintain proper hilling', 'Balance NPK fertilization', 'Monitor regularly for blight symptoms'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Follow National Potato Research Program recommendations for your agro-ecological zone.',
        'medicines': [],
    },
    # ── Raspberry ──
    {
        'class_label': 'Raspberry___healthy',
        'crop': 'Raspberry',
        'name': 'Raspberry___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The raspberry leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Prune out old floricanes after harvest', 'Maintain good air circulation', 'Mulch to retain moisture'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Raspberry cultivation in Nepal is limited and experimental. Suitable for cooler high-altitude areas.',
        'medicines': [],
    },
    # ── Soybean ──
    {
        'class_label': 'Soybean___healthy',
        'crop': 'Soybean',
        'name': 'Soybean___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The soybean leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Inoculate seed with Rhizobium', 'Rotate with cereal crops', 'Monitor for defoliating insects'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Soybean is an important legume crop in Nepal\'s mid-hills. Follow NARC recommendations.',
        'medicines': [],
    },
    # ── Squash ──
    {
        'class_label': 'Squash___Powdery_mildew',
        'crop': 'Squash',
        'name': 'Squash___Powdery_mildew',
        'scientific_name': 'Podosphaera xanthii / Erysiphe cichoracearum',
        'description': 'Powdery mildew on squash appears as white powdery patches on leaves, petioles, and stems, reducing photosynthesis and fruit quality.',
        'symptoms': ['White powdery spots on upper leaf surfaces', 'Spots expand to cover entire leaf', 'Yellowing and browning of severely affected leaves', 'Premature leaf drop'],
        'causes': ['Warm dry conditions with cool nights', 'Dense planting', 'Shaded or poorly ventilated growing areas'],
        'organic_treatments': ['Potassium bicarbonate spray', 'Neem oil', 'Sulfur-based fungicides', 'Milk spray (1:9 milk:water)'],
        'chemical_treatments': ['Sulfur 80% WP', 'Chlorothalonil spray'],
        'prevention_tips': ['Plant resistant varieties', 'Ensure adequate spacing', 'Avoid excessive nitrogen', 'Water at base of plants'],
        'affected_parts': ['Leaves', 'Stems', 'Petioles'],
        'severity': 'Medium',
        'duration': '3-6 weeks',
        'weather': 'Warm days, cool nights, moderate humidity',
        'regional_recommendation': '⚠ REVIEW: Cucurbit powdery mildew is very common in Nepal. Sulfur sprays are effective and widely available.',
        'medicines': ['Sulfur 80% WP', 'Neem Oil'],
    },
    # ── Strawberry ──
    {
        'class_label': 'Strawberry___Leaf_scorch',
        'crop': 'Strawberry',
        'name': 'Strawberry___Leaf_scorch',
        'scientific_name': 'Diplocarpon earlianum',
        'description': 'Leaf scorch causes irregular purplish spots that merge into large necrotic areas, giving a scorched appearance. Severe infection weakens plants.',
        'symptoms': ['Small irregular dark purple spots', 'Spots coalesce into large scorched areas', 'Leaf margins turn brown', 'Severely affected leaves dry up and die'],
        'causes': ['Fungus overwinters in infected leaves', 'Warm wet weather', 'Overhead irrigation promoting leaf wetness'],
        'organic_treatments': ['Remove infected leaves', 'Neem oil spray', 'Bordeaux mixture'],
        'chemical_treatments': ['Mancozeb spray', 'Copper-based fungicides'],
        'prevention_tips': ['Remove old infected leaves', 'Use drip irrigation instead of overhead', 'Maintain proper plant spacing', 'Use certified disease-free transplants'],
        'affected_parts': ['Leaves', 'Petioles', 'Runners'],
        'severity': 'Medium',
        'duration': '3-5 weeks',
        'weather': 'Warm and humid',
        'regional_recommendation': '⚠ REVIEW: Strawberry is an emerging high-value crop in Nepal (Nagarkot, Kakani, Daman). Disease management is essential for quality production.',
        'medicines': ['Mancozeb 75% WP', 'Bordeaux Mixture', 'Neem Oil'],
    },
    {
        'class_label': 'Strawberry___healthy',
        'crop': 'Strawberry',
        'name': 'Strawberry___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The strawberry leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Use mulch to prevent soil splash', 'Maintain proper spacing', 'Remove runners for better fruit quality'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Follow strawberry production guidelines for Nepal\'s peri-urban farming zones.',
        'medicines': [],
    },
    # ── Tomato ──
    {
        'class_label': 'Tomato___Bacterial_spot',
        'crop': 'Tomato',
        'name': 'Tomato___Bacterial_spot',
        'scientific_name': 'Xanthomonas vesicatoria',
        'description': 'Bacterial spot causes small dark water-soaked lesions on leaves, stems, and fruit, leading to defoliation and unmarketable fruit.',
        'symptoms': ['Small water-soaked spots on leaves', 'Spots become dark brown with yellow halo', 'Raised scab-like spots on fruit', 'Defoliation in severe cases'],
        'causes': ['Bacterium spread by rain splash and handling', 'Warm humid conditions', 'Contaminated seed'],
        'organic_treatments': ['Copper sprays (Bordeaux mixture)', 'Remove infected plant debris', 'Use disease-free seed'],
        'chemical_treatments': ['Copper oxychloride spray', 'Streptomycin sulphate (where permitted)'],
        'prevention_tips': ['Use certified disease-free seed and transplants', 'Avoid overhead irrigation', 'Rotate with non-solanaceous crops (3-year)', 'Sanitize tools'],
        'affected_parts': ['Leaves', 'Fruit', 'Stems'],
        'severity': 'Medium',
        'duration': 'Growing season',
        'weather': 'Warm and humid (24-30°C)',
        'regional_recommendation': '⚠ REVIEW: Common in Nepal\'s tomato-growing regions. Copper-based sprays are the primary tool. Follow VDD/NARC IPM guidelines.',
        'medicines': ['Copper Oxychloride 50% WP', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Tomato___Early_blight',
        'crop': 'Tomato',
        'name': 'Tomato___Early_blight',
        'scientific_name': 'Alternaria solani',
        'description': 'Early blight of tomato produces characteristic concentric ring (target-spot) lesions on older leaves, progressing upward and reducing fruit yield.',
        'symptoms': ['Dark brown spots with concentric rings on lower leaves', 'Yellowing around lesions', 'Collar rot at soil line in seedlings', 'Dark sunken lesions on fruit near stem end'],
        'causes': ['Fungus survives in soil and crop debris', 'Warm temperatures with alternating wet/dry conditions', 'Nutrient-stressed plants are more susceptible'],
        'organic_treatments': ['Trichoderma viride soil application', 'Neem oil spray', 'Bordeaux mixture', 'Remove lower affected leaves'],
        'chemical_treatments': ['Mancozeb 75% WP at 7-10 day intervals', 'Chlorothalonil spray'],
        'prevention_tips': ['Rotate crops (avoid solanaceous crops for 3 years)', 'Stake and prune plants for air circulation', 'Mulch to prevent soil splash', 'Use resistant varieties'],
        'affected_parts': ['Leaves', 'Stems', 'Fruit'],
        'severity': 'Medium',
        'duration': '3-5 weeks per cycle',
        'weather': 'Warm (24-29°C) with wet/dry alternation',
        'regional_recommendation': '⚠ REVIEW: One of the most common tomato diseases in Nepal. Mancozeb is widely available. NARC recommends starting spray at first symptoms on lower leaves.',
        'medicines': ['Mancozeb 75% WP', 'Chlorothalonil 75% WP', 'Trichoderma viride', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Tomato___Late_blight',
        'crop': 'Tomato',
        'name': 'Tomato___Late_blight',
        'scientific_name': 'Phytophthora infestans',
        'description': 'Late blight is a devastating oomycete disease causing rapidly expanding water-soaked lesions with white fuzzy growth, capable of destroying entire crops.',
        'symptoms': ['Water-soaked pale green lesions on leaves', 'White fuzzy sporulation on leaf undersides', 'Rapid browning and death of leaves', 'Brown firm rot on fruit'],
        'causes': ['Cool wet weather (10-20°C)', 'Persistent leaf wetness', 'Infected potato or tomato nearby'],
        'organic_treatments': ['Bordeaux mixture spray', 'Remove and destroy infected plants', 'Copper-based sprays'],
        'chemical_treatments': ['Metalaxyl + Mancozeb (Ridomil Gold)', 'Mancozeb spray at 5-7 day intervals in wet weather'],
        'prevention_tips': ['Use resistant varieties', 'Provide good air circulation (staking and spacing)', 'Avoid overhead irrigation', 'Remove volunteer tomato and potato plants', 'Plant away from potato fields'],
        'affected_parts': ['Leaves', 'Stems', 'Fruit'],
        'severity': 'Critical',
        'duration': 'Can destroy crop in 7-10 days',
        'weather': 'Cool (10-20°C) and persistently wet',
        'regional_recommendation': '⚠ REVIEW: CRITICAL for Nepal. Late blight devastates tomato crops during the monsoon, especially in mid-hill tunnel houses. Metalaxyl+Mancozeb (Ridomil Gold) is the recommended systemic treatment. Contact VDD/NARC for resistant variety recommendations.',
        'medicines': ['Metalaxyl + Mancozeb (Ridomil Gold)', 'Mancozeb 75% WP', 'Bordeaux Mixture', 'Copper Oxychloride 50% WP'],
    },
    {
        'class_label': 'Tomato___Leaf_Mold',
        'crop': 'Tomato',
        'name': 'Tomato___Leaf_Mold',
        'scientific_name': 'Passalora fulva (syn. Cladosporium fulvum)',
        'description': 'Leaf mold causes yellow spots on upper leaf surfaces with olive-green to grayish-purple fuzzy mold on the undersides, primarily in humid greenhouse conditions.',
        'symptoms': ['Pale yellow spots on upper leaf surface', 'Olive-green to purple fuzzy mold on leaf undersides', 'Leaves curl, wither, and drop', 'Occasionally affects fruit (rare)'],
        'causes': ['High humidity (>85% RH)', 'Poor ventilation in greenhouses/tunnels', 'Temperatures 20-25°C', 'Dense plant canopy'],
        'organic_treatments': ['Improve greenhouse ventilation', 'Remove infected leaves', 'Trichoderma application'],
        'chemical_treatments': ['Mancozeb spray', 'Chlorothalonil application'],
        'prevention_tips': ['Ensure proper ventilation in greenhouses', 'Avoid leaf wetness', 'Space plants adequately', 'Use resistant varieties'],
        'affected_parts': ['Leaves'],
        'severity': 'Medium',
        'duration': '3-4 weeks under favorable conditions',
        'weather': 'High humidity, moderate temperature',
        'regional_recommendation': '⚠ REVIEW: Common in Nepal\'s plastic tunnel tomato production. Good ventilation management is the primary control strategy.',
        'medicines': ['Mancozeb 75% WP', 'Chlorothalonil 75% WP', 'Trichoderma viride'],
    },
    {
        'class_label': 'Tomato___Septoria_leaf_spot',
        'crop': 'Tomato',
        'name': 'Tomato___Septoria_leaf_spot',
        'scientific_name': 'Septoria lycopersici',
        'description': 'Septoria leaf spot produces numerous small circular spots with gray centers and dark borders on lower leaves, progressing upward and causing defoliation.',
        'symptoms': ['Numerous small circular spots (1-3 mm)', 'Spots have gray/tan centers with dark brown margins', 'Tiny dark pycnidia (fruiting bodies) visible in spot centers', 'Lower leaves affected first, progressing upward'],
        'causes': ['Fungus survives in crop debris', 'Wet conditions with temperatures 20-25°C', 'Overhead irrigation promoting leaf wetness'],
        'organic_treatments': ['Remove lower infected leaves', 'Bordeaux mixture spray', 'Trichoderma application to soil'],
        'chemical_treatments': ['Mancozeb 75% WP spray', 'Chlorothalonil application'],
        'prevention_tips': ['Rotate crops (3-year)', 'Remove crop residues', 'Mulch to prevent soil splash', 'Use drip irrigation', 'Stake plants'],
        'affected_parts': ['Leaves', 'Stems'],
        'severity': 'Medium',
        'duration': '3-5 weeks',
        'weather': 'Warm and wet (20-25°C)',
        'regional_recommendation': '⚠ REVIEW: Widely prevalent in Nepal\'s tomato fields. Mancozeb is the standard treatment. Staking and mulching significantly reduce infection.',
        'medicines': ['Mancozeb 75% WP', 'Chlorothalonil 75% WP', 'Bordeaux Mixture'],
    },
    {
        'class_label': 'Tomato___Spider_mites Two-spotted_spider_mite',
        'crop': 'Tomato',
        'name': 'Tomato___Spider_mites Two-spotted_spider_mite',
        'scientific_name': 'Tetranychus urticae',
        'description': 'Two-spotted spider mite infestation causes stippling (tiny yellow dots) on leaves from mite feeding, followed by webbing and leaf desiccation under heavy infestation.',
        'symptoms': ['Fine stippling (tiny yellow/white dots) on upper leaf surface', 'Bronzing and drying of leaves', 'Fine webbing on leaf undersides and between leaves', 'Stunted growth in severe infestations'],
        'causes': ['Hot dry conditions', 'Dusty environments', 'Excessive use of broad-spectrum insecticides (kills natural predators)', 'Water stress'],
        'organic_treatments': ['Strong water spray to dislodge mites', 'Neem oil spray', 'Introduce predatory mites (Phytoseiulus persimilis)', 'Sulfur spray'],
        'chemical_treatments': ['Abamectin 1.8% EC', 'Sulfur 80% WP'],
        'prevention_tips': ['Maintain adequate irrigation', 'Avoid dusty conditions near fields', 'Preserve natural predators — avoid broad-spectrum insecticides', 'Monitor undersides of leaves regularly'],
        'affected_parts': ['Leaves', 'Stems'],
        'severity': 'Medium',
        'duration': 'Can build up rapidly in 2-3 weeks under hot dry conditions',
        'weather': 'Hot and dry',
        'regional_recommendation': '⚠ REVIEW: Spider mites are a significant pest in Nepal\'s dry season tomato and tunnel-house production. Abamectin (Vertimec) is available through agrovets.',
        'medicines': ['Abamectin 1.8% EC', 'Neem Oil', 'Sulfur 80% WP'],
    },
    {
        'class_label': 'Tomato___Target_Spot',
        'crop': 'Tomato',
        'name': 'Tomato___Target_Spot',
        'scientific_name': 'Corynespora cassiicola',
        'description': 'Target spot causes circular brown spots with concentric rings on leaves, stems, and fruit. It can be confused with early blight.',
        'symptoms': ['Small water-soaked spots enlarging to brown lesions', 'Concentric ring pattern (target-like)', 'Lesions on leaves, stems, and fruit', 'Defoliation starting from lower canopy'],
        'causes': ['Warm humid conditions', 'Dense canopy with poor air circulation', 'Fungus persists in crop debris and soil'],
        'organic_treatments': ['Remove infected leaves and debris', 'Improve air circulation', 'Trichoderma application', 'Neem oil spray'],
        'chemical_treatments': ['Mancozeb 75% WP', 'Chlorothalonil spray'],
        'prevention_tips': ['Prune lower leaves for air circulation', 'Use plastic mulch', 'Rotate crops', 'Use drip irrigation'],
        'affected_parts': ['Leaves', 'Stems', 'Fruit'],
        'severity': 'Medium',
        'duration': '3-5 weeks',
        'weather': 'Warm and humid',
        'regional_recommendation': '⚠ REVIEW: Increasingly reported in Nepal\'s tomato production areas. Management is similar to early blight.',
        'medicines': ['Mancozeb 75% WP', 'Chlorothalonil 75% WP', 'Trichoderma viride'],
    },
    {
        'class_label': 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
        'crop': 'Tomato',
        'name': 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
        'scientific_name': 'Tomato yellow leaf curl virus (TYLCV)',
        'description': 'TYLCV is a devastating viral disease transmitted by whiteflies (Bemisia tabaci), causing severe leaf curling, yellowing, and stunting with near-total crop loss.',
        'symptoms': ['Severe upward curling of leaf margins', 'Yellowing of leaf edges and interveinal areas', 'Stunted plant growth', 'Flower drop and little to no fruit set', 'Leathery texture of leaves'],
        'causes': ['Whitefly (Bemisia tabaci) transmission', 'Movement of infected transplants', 'High whitefly populations in warm weather'],
        'organic_treatments': ['Install yellow sticky traps for whitefly monitoring', 'Neem oil spray for whitefly control', 'Remove and destroy infected plants', 'Use reflective mulch to repel whiteflies'],
        'chemical_treatments': ['Imidacloprid 17.8% SL for whitefly vector control', 'No cure for the virus itself'],
        'prevention_tips': ['Use TYLCV-resistant varieties', 'Control whitefly population aggressively', 'Use insect-proof net houses/tunnels', 'Remove infected plants immediately', 'Avoid planting near other infected solanaceous crops'],
        'affected_parts': ['Leaves', 'Entire plant (systemic virus)'],
        'severity': 'Critical',
        'duration': 'Chronic — infected plants do not recover',
        'weather': 'Year-round in warm climates, peaks in dry warm seasons',
        'regional_recommendation': '⚠ REVIEW: TYLCV is a major emerging threat to Nepal\'s tomato industry, particularly in the Terai. Whitefly management and use of resistant varieties (from NARC/HRD) are essential. Insect-proof net tunnels are highly recommended.',
        'medicines': ['Imidacloprid 17.8% SL', 'Neem Oil'],
    },
    {
        'class_label': 'Tomato___Tomato_mosaic_virus',
        'crop': 'Tomato',
        'name': 'Tomato___Tomato_mosaic_virus',
        'scientific_name': 'Tomato mosaic virus (ToMV)',
        'description': 'Tomato mosaic virus causes mottled light and dark green patterns on leaves, leaf distortion, and reduced fruit quality. It is highly contagious through mechanical contact.',
        'symptoms': ['Mosaic pattern of light and dark green on leaves', 'Leaf distortion and curling', 'Reduced fruit size and quality', 'Fernleaf symptoms in some strains', 'Internal browning of fruit'],
        'causes': ['Mechanical transmission through handling', 'Contaminated seeds', 'Contact with infected plant sap', 'Very stable virus — persists on tools and surfaces'],
        'organic_treatments': ['Remove and destroy infected plants', 'Disinfect tools with 10% bleach solution', 'Wash hands with soap between handling plants', 'Milk spray (1:4 milk:water) on hands and tools'],
        'chemical_treatments': ['No chemical cure — manage through prevention and sanitation'],
        'prevention_tips': ['Use virus-free certified seed', 'Disinfect tools between plants', 'Wash hands with soap and water before handling plants', 'Do not smoke near plants (tobacco mosaic cross-infection)', 'Use resistant varieties'],
        'affected_parts': ['Leaves', 'Fruit', 'Entire plant (systemic)'],
        'severity': 'High',
        'duration': 'Chronic — infected plants do not recover',
        'weather': 'Any conditions (spread is mechanical, not weather-dependent)',
        'regional_recommendation': '⚠ REVIEW: ToMV is present in Nepal. Strict hygiene and use of certified seed are the most effective control measures. No chemical cure exists.',
        'medicines': [],
    },
    {
        'class_label': 'Tomato___healthy',
        'crop': 'Tomato',
        'name': 'Tomato___healthy',
        'scientific_name': '',
        'description': 'No disease detected. The tomato leaf appears healthy.',
        'symptoms': [],
        'causes': [],
        'organic_treatments': [],
        'chemical_treatments': [],
        'prevention_tips': ['Maintain proper staking and spacing', 'Use balanced NPK fertilization', 'Monitor regularly for pests and diseases', 'Practice crop rotation'],
        'affected_parts': [],
        'severity': 'Low',
        'duration': '',
        'weather': '',
        'regional_recommendation': '⚠ REVIEW: Follow VDD/NARC tomato production packages for your agro-ecological zone in Nepal.',
        'medicines': [],
    },
]


def run():
    print('=' * 60)
    print(' AgriVision AI — Database Population Script')
    print('=' * 60)

    # 1. Create crops
    print('\n[1/3] Creating crops...')
    crop_objects = {}
    for name, sci_name in CROPS.items():
        obj, created = Crop.objects.update_or_create(
            name=name, defaults={'scientific_name': sci_name}
        )
        crop_objects[name] = obj
        status_label = 'CREATED' if created else 'EXISTS'
        print(f'  {status_label}: {name} ({sci_name})')

    # 2. Create medicines
    print('\n[2/3] Creating medicines...')
    medicine_objects = {}
    for med_data in MEDICINES_DATA:
        obj, created = Medicine.objects.update_or_create(
            name=med_data['name'],
            defaults={
                'type': med_data['type'],
                'active_ingredients': med_data.get('active_ingredients', ''),
                'manufacturer': med_data.get('manufacturer', ''),
                'dosage_guidance': med_data.get('dosage_guidance', ''),
                'application_method': med_data.get('application_method', ''),
                'safety_precautions': med_data.get('safety_precautions', ''),
                'description': med_data.get('description', ''),
            }
        )
        medicine_objects[med_data['name']] = obj
        status_label = 'CREATED' if created else 'UPDATED'
        print(f'  {status_label}: {med_data["name"]} [{med_data["type"]}]')

    # 3. Create diseases and link medicines
    print('\n[3/3] Creating diseases and linking medicines...')
    for d in DISEASE_DATA:
        crop = crop_objects.get(d['crop'])
        if not crop:
            print(f'  ⚠ SKIP: Crop "{d["crop"]}" not found for disease "{d["name"]}"')
            continue

        disease, created = Disease.objects.update_or_create(
            name=d['name'],
            defaults={
                'crop': crop,
                'scientific_name': d.get('scientific_name', ''),
                'description': d.get('description', ''),
                'symptoms': d.get('symptoms', []),
                'causes': d.get('causes', []),
                'organic_treatments': d.get('organic_treatments', []),
                'chemical_treatments': d.get('chemical_treatments', []),
                'prevention_tips': d.get('prevention_tips', []),
                'affected_parts': d.get('affected_parts', []),
                'duration': d.get('duration', ''),
                'weather': d.get('weather', ''),
                'severity': d.get('severity', 'Medium'),
                'regional_recommendation': d.get('regional_recommendation', ''),
            }
        )
        status_label = 'CREATED' if created else 'UPDATED'
        print(f'  {status_label}: {d["name"]}')

        # Link medicines
        for med_name in d.get('medicines', []):
            med = medicine_objects.get(med_name)
            if med:
                DiseaseMedicineMapping.objects.get_or_create(disease=disease, medicine=med)

    print('\n' + '=' * 60)
    total_crops = Crop.objects.count()
    total_diseases = Disease.objects.count()
    total_medicines = Medicine.objects.count()
    total_mappings = DiseaseMedicineMapping.objects.count()
    print(f' Done! {total_crops} crops, {total_diseases} diseases, '
          f'{total_medicines} medicines, {total_mappings} disease-medicine links.')
    print('=' * 60)


if __name__ == '__main__':
    run()
